BEGIN TRAN;

-- 1) Borrar detalle primero (si tiene FK a ARTICULO)
DELETE FROM MOVIMIENTO_STOCK;
DELETE FROM STOCK;

-- 2) Borrar maestro
DELETE FROM ARTICULO;

-- 3) Reseed de la identidad de ARTICULO
DBCC CHECKIDENT ('ARTICULO', RESEED, 0);
DBCC CHECKIDENT ('STOCK', RESEED, 0);
DBCC CHECKIDENT ('MOVIMIENTO_STOCK', RESEED, 0);

