-- =========================================================
-- RECETAS (BOM): insumos necesarios para producir un producto terminado
-- =========================================================

CREATE TABLE IF NOT EXISTS receta (
  id_receta integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_producto_terminado integer NOT NULL REFERENCES articulo(id_articulo),
  nombre varchar(150) NOT NULL,
  activa boolean NOT NULL DEFAULT true,
  fecha_creacion timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS receta_item (
  id_receta_item integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_receta integer NOT NULL REFERENCES receta(id_receta) ON DELETE CASCADE,
  id_articulo integer NOT NULL REFERENCES articulo(id_articulo),
  cantidad_por_unidad numeric(18,4) NOT NULL CHECK (cantidad_por_unidad > 0),
  CONSTRAINT uq_receta_item UNIQUE (id_receta, id_articulo)
);

CREATE INDEX IF NOT EXISTS ix_receta_pt ON receta(id_producto_terminado);

-- Ubicación de stock según la categoría del insumo (10=materia prima, 30=subensamble)
CREATE OR REPLACE FUNCTION inv_location_code_for_categoria(codigo_categoria text)
RETURNS text
LANGUAGE plpgsql
AS $$
BEGIN
  IF codigo_categoria = '10' THEN RETURN 'CONSUMIBLES';
  ELSIF codigo_categoria = '30' THEN RETURN 'SUBENSAMBLE';
  ELSIF codigo_categoria = '40' THEN RETURN 'STOCK';
  END IF;
  RAISE EXCEPTION 'Categoría sin ubicación configurada';
END;
$$;

-- Crear / editar una receta (reemplaza todos sus insumos)
CREATE OR REPLACE FUNCTION inv_receta_upsert(
  id_receta integer DEFAULT NULL,
  id_producto_terminado integer DEFAULT NULL,
  nombre text DEFAULT NULL,
  items jsonb DEFAULT '[]'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
AS $$
DECLARE
  pt_cat_id integer;
  v_id_receta integer;
  item jsonb;
  v_id_articulo integer;
  v_cantidad numeric;
  v_categoria_codigo text;
BEGIN
  SELECT id_categoria INTO pt_cat_id FROM categoria WHERE codigo_categoria = '40' AND activo = true;

  PERFORM 1 FROM articulo a
  WHERE a.id_articulo = inv_receta_upsert.id_producto_terminado
    AND a.id_categoria = pt_cat_id AND a.activo = true;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Producto terminado inválido';
  END IF;

  IF nombre IS NULL OR BTRIM(nombre) = '' THEN
    RAISE EXCEPTION 'Nombre de receta requerido';
  END IF;

  IF jsonb_array_length(COALESCE(items, '[]'::jsonb)) = 0 THEN
    RAISE EXCEPTION 'La receta necesita al menos un insumo';
  END IF;

  IF id_receta IS NULL THEN
    INSERT INTO receta (id_producto_terminado, nombre, activa)
    VALUES (inv_receta_upsert.id_producto_terminado, UPPER(BTRIM(nombre)), true)
    RETURNING receta.id_receta INTO v_id_receta;
  ELSE
    UPDATE receta SET nombre = UPPER(BTRIM(nombre))
    WHERE receta.id_receta = inv_receta_upsert.id_receta
    RETURNING receta.id_receta INTO v_id_receta;

    IF v_id_receta IS NULL THEN
      RAISE EXCEPTION 'Receta no encontrada';
    END IF;
    DELETE FROM receta_item WHERE receta_item.id_receta = v_id_receta;
  END IF;

  FOR item IN SELECT * FROM jsonb_array_elements(items)
  LOOP
    v_id_articulo := (item->>'id_articulo')::integer;
    v_cantidad := (item->>'cantidad_por_unidad')::numeric;

    IF v_id_articulo IS NULL OR v_cantidad IS NULL OR v_cantidad <= 0 THEN
      RAISE EXCEPTION 'Insumo inválido en la receta';
    END IF;
    IF v_id_articulo = inv_receta_upsert.id_producto_terminado THEN
      RAISE EXCEPTION 'Un producto terminado no puede ser insumo de sí mismo';
    END IF;

    SELECT c.codigo_categoria INTO v_categoria_codigo
    FROM articulo a JOIN categoria c ON c.id_categoria = a.id_categoria
    WHERE a.id_articulo = v_id_articulo AND a.activo = true;

    IF v_categoria_codigo IS NULL OR v_categoria_codigo NOT IN ('10', '30') THEN
      RAISE EXCEPTION 'El insumo % no es materia prima ni subensamble', v_id_articulo;
    END IF;

    INSERT INTO receta_item (id_receta, id_articulo, cantidad_por_unidad)
    VALUES (v_id_receta, v_id_articulo, v_cantidad);
  END LOOP;

  RETURN jsonb_build_object('ok', true, 'id_receta', v_id_receta);
END;
$$;

CREATE OR REPLACE FUNCTION inv_receta_set_active(id_receta integer, activa boolean)
RETURNS jsonb LANGUAGE plpgsql AS $$
BEGIN
  UPDATE receta SET activa = inv_receta_set_active.activa
  WHERE receta.id_receta = inv_receta_set_active.id_receta;
  IF NOT FOUND THEN RAISE EXCEPTION 'Receta no encontrada'; END IF;
  RETURN jsonb_build_object('ok', true);
END; $$;

CREATE OR REPLACE FUNCTION inv_receta_delete(id_receta integer)
RETURNS jsonb LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM receta WHERE receta.id_receta = inv_receta_delete.id_receta;
  IF NOT FOUND THEN RAISE EXCEPTION 'Receta no encontrada'; END IF;
  RETURN jsonb_build_object('ok', true);
END; $$;

-- Listar recetas (opcionalmente filtradas por producto terminado), con stock actual de cada insumo
CREATE OR REPLACE FUNCTION inv_receta_list(id_producto_terminado integer DEFAULT NULL)
RETURNS jsonb
LANGUAGE sql
AS $$
  SELECT COALESCE(jsonb_agg(r ORDER BY r->>'nombre'), '[]'::jsonb)
  FROM (
    SELECT jsonb_build_object(
      'id_receta', rc.id_receta,
      'id_producto_terminado', rc.id_producto_terminado,
      'producto_terminado', pt.nombre_base,
      'nombre', rc.nombre,
      'activa', rc.activa,
      'items', COALESCE((
        SELECT jsonb_agg(jsonb_build_object(
          'id_articulo', ri.id_articulo,
          'nombre', a.nombre_base,
          'unidad_medida', a.unidad_medida,
          'cantidad_por_unidad', ri.cantidad_por_unidad,
          'stock_actual', COALESCE(s.cantidad_actual, 0)
        ) ORDER BY a.nombre_base)
        FROM receta_item ri
        JOIN articulo a ON a.id_articulo = ri.id_articulo
        JOIN categoria c ON c.id_categoria = a.id_categoria
        LEFT JOIN ubicacion u
          ON u.codigo_ubicacion = inv_location_code_for_categoria(c.codigo_categoria) AND u.activa = true
        LEFT JOIN stock s ON s.id_articulo = ri.id_articulo AND s.id_ubicacion = u.id_ubicacion
        WHERE ri.id_receta = rc.id_receta
      ), '[]'::jsonb)
    ) AS r
    FROM receta rc
    JOIN articulo pt ON pt.id_articulo = rc.id_producto_terminado
    WHERE (inv_receta_list.id_producto_terminado IS NULL
           OR rc.id_producto_terminado = inv_receta_list.id_producto_terminado)
  ) x;
$$;

-- Fabricar producto terminado consumiendo los insumos de una receta
CREATE OR REPLACE FUNCTION inv_fabricate_from_receta(
  id_receta integer,
  cantidad numeric,
  referencia text DEFAULT 'FABRICACION',
  observaciones text DEFAULT NULL,
  id_usuario integer DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
AS $$
DECLARE
  qty numeric;
  v_id_producto_terminado integer;
  v_activa boolean;
  pt_loc_id integer;
  pt_before numeric;
  pt_min numeric;
  pt_max numeric;
  pt_after numeric;
  r RECORD;
  consumo jsonb := '[]'::jsonb;
  item_before numeric;
  item_loc_id integer;
  item_needed numeric;
  item_after numeric;
BEGIN
  qty := COALESCE(cantidad, 0);
  IF qty <= 0 THEN
    RAISE EXCEPTION 'Cantidad inválida';
  END IF;

  SELECT rc.id_producto_terminado, rc.activa
  INTO v_id_producto_terminado, v_activa
  FROM receta rc
  WHERE rc.id_receta = inv_fabricate_from_receta.id_receta;

  IF v_id_producto_terminado IS NULL THEN
    RAISE EXCEPTION 'Receta no encontrada';
  END IF;
  IF NOT v_activa THEN
    RAISE EXCEPTION 'La receta no está activa';
  END IF;

  SELECT id_ubicacion INTO pt_loc_id FROM ubicacion WHERE codigo_ubicacion = 'STOCK' AND activa = true;
  IF pt_loc_id IS NULL THEN
    RAISE EXCEPTION 'Ubicaciones no configuradas';
  END IF;

  -- Paso 1: validar disponibilidad de TODOS los insumos antes de tocar nada
  FOR r IN
    SELECT ri.id_articulo, ri.cantidad_por_unidad, a.nombre_base,
           inv_location_code_for_categoria(c.codigo_categoria) AS ubicacion_codigo
    FROM receta_item ri
    JOIN articulo a ON a.id_articulo = ri.id_articulo
    JOIN categoria c ON c.id_categoria = a.id_categoria
    WHERE ri.id_receta = inv_fabricate_from_receta.id_receta
  LOOP
    item_needed := r.cantidad_por_unidad * qty;
    SELECT id_ubicacion INTO item_loc_id FROM ubicacion WHERE codigo_ubicacion = r.ubicacion_codigo AND activa = true;
    SELECT COALESCE(s.cantidad_actual, 0) INTO item_before
    FROM stock s WHERE s.id_articulo = r.id_articulo AND s.id_ubicacion = item_loc_id;

    IF COALESCE(item_before, 0) < item_needed THEN
      RAISE EXCEPTION 'No hay suficiente stock de % (disponible: %, requerido: %)',
        r.nombre_base, COALESCE(item_before, 0), item_needed;
    END IF;
  END LOOP;

  -- Paso 2: consumir insumos
  FOR r IN
    SELECT ri.id_articulo, ri.cantidad_por_unidad, a.nombre_base,
           inv_location_code_for_categoria(c.codigo_categoria) AS ubicacion_codigo
    FROM receta_item ri
    JOIN articulo a ON a.id_articulo = ri.id_articulo
    JOIN categoria c ON c.id_categoria = a.id_categoria
    WHERE ri.id_receta = inv_fabricate_from_receta.id_receta
  LOOP
    item_needed := r.cantidad_por_unidad * qty;
    SELECT id_ubicacion INTO item_loc_id FROM ubicacion WHERE codigo_ubicacion = r.ubicacion_codigo AND activa = true;

    SELECT COALESCE(s.cantidad_actual, 0) INTO item_before
    FROM stock s WHERE s.id_articulo = r.id_articulo AND s.id_ubicacion = item_loc_id
    FOR UPDATE;

    item_after := item_before - item_needed;

    UPDATE stock SET cantidad_actual = item_after, fecha_ultima_actualizacion = now()
    WHERE id_articulo = r.id_articulo AND id_ubicacion = item_loc_id;

    INSERT INTO movimiento_stock (
      tipo_movimiento, id_articulo, id_ubicacion_origen, id_ubicacion_destino,
      cantidad, referencia, id_usuario, observaciones
    ) VALUES (
      'FAB_RECETA_SALIDA', r.id_articulo, item_loc_id, pt_loc_id, item_needed,
      NULLIF(BTRIM(referencia), ''), id_usuario, NULLIF(BTRIM(observaciones), '')
    );

    consumo := consumo || jsonb_build_object(
      'id_articulo', r.id_articulo, 'nombre', r.nombre_base,
      'antes', item_before, 'despues', item_after, 'consumido', item_needed
    );
  END LOOP;

  -- Paso 3: acreditar el producto terminado
  INSERT INTO stock (id_articulo, id_ubicacion, cantidad_actual, minimo, maximo, punto_reorden)
  VALUES (v_id_producto_terminado, pt_loc_id, 0, 0, 0, 0)
  ON CONFLICT (id_articulo, id_ubicacion) DO NOTHING;

  SELECT COALESCE(s.cantidad_actual, 0), COALESCE(s.minimo, 0), COALESCE(s.maximo, 0)
  INTO pt_before, pt_min, pt_max
  FROM stock s WHERE s.id_articulo = v_id_producto_terminado AND s.id_ubicacion = pt_loc_id
  FOR UPDATE;

  pt_after := pt_before + qty;

  UPDATE stock SET cantidad_actual = pt_after, fecha_ultima_actualizacion = now()
  WHERE id_articulo = v_id_producto_terminado AND id_ubicacion = pt_loc_id;

  INSERT INTO movimiento_stock (
    tipo_movimiento, id_articulo, id_ubicacion_origen, id_ubicacion_destino,
    cantidad, referencia, id_usuario, observaciones
  ) VALUES (
    'FAB_RECETA_ENTRADA', v_id_producto_terminado, NULL, pt_loc_id, qty,
    NULLIF(BTRIM(referencia), ''), id_usuario, NULLIF(BTRIM(observaciones), '')
  );

  RETURN jsonb_build_object(
    'ok', true, 'id_receta', inv_fabricate_from_receta.id_receta, 'cantidad', qty,
    'consumo', consumo,
    'producto_terminado', jsonb_build_object(
      'id_articulo', v_id_producto_terminado, 'antes', pt_before, 'despues', pt_after,
      'minimo', pt_min, 'maximo', pt_max, 'bajo_minimo', (pt_after < pt_min)
    )
  );
END;
$$;