CREATE TABLE IF NOT EXISTS categoria (
  id_categoria integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_categoria char(2) NOT NULL UNIQUE,
  nombre_categoria varchar(100) NOT NULL,
  activo boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS subcategoria (
  id_subcategoria integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_categoria integer NOT NULL REFERENCES categoria(id_categoria),
  codigo_subcategoria char(3) NOT NULL,
  nombre_subcategoria varchar(100) NOT NULL,
  activo boolean NOT NULL DEFAULT true,
  CONSTRAINT uq_subcat UNIQUE (id_categoria, codigo_subcategoria)
);

CREATE TABLE IF NOT EXISTS articulo (
  id_articulo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_articulo bigint NOT NULL UNIQUE,
  codigo_sap bigint NULL,
  id_categoria integer NOT NULL REFERENCES categoria(id_categoria),
  id_subcategoria integer NOT NULL REFERENCES subcategoria(id_subcategoria),
  nombre_base varchar(150) NOT NULL,
  descripcion varchar(255) NULL,
  dimension_principal varchar(50) NULL,
  detalle_adicional varchar(255) NULL,
  unidad_medida varchar(20) NOT NULL,
  es_maquinaria boolean NOT NULL DEFAULT false,
  es_herramienta boolean NOT NULL DEFAULT false,
  es_consumible boolean NOT NULL DEFAULT false,
  activo boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS ubicacion (
  id_ubicacion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_ubicacion varchar(50) NOT NULL UNIQUE,
  nombre_ubicacion varchar(150) NOT NULL,
  tipo_ubicacion varchar(50) NOT NULL,
  activa boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS stock (
  id_stock integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_articulo integer NOT NULL REFERENCES articulo(id_articulo),
  id_ubicacion integer NOT NULL REFERENCES ubicacion(id_ubicacion),
  cantidad_actual numeric(18,3) NOT NULL DEFAULT 0,
  minimo numeric(18,3) NOT NULL DEFAULT 0,
  maximo numeric(18,3) NOT NULL DEFAULT 0,
  punto_reorden numeric(18,3) NOT NULL DEFAULT 0,
  fecha_ultima_actualizacion timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_stock UNIQUE (id_articulo, id_ubicacion)
);

CREATE TABLE IF NOT EXISTS usuario (
  id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(50) NOT NULL UNIQUE,
  password_hash varchar(255) NOT NULL,
  activo boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS movimiento_stock (
  id_movimiento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_hora timestamptz NOT NULL DEFAULT now(),
  tipo_movimiento varchar(20) NOT NULL,
  id_articulo integer NOT NULL REFERENCES articulo(id_articulo),
  id_ubicacion_origen integer NULL REFERENCES ubicacion(id_ubicacion),
  id_ubicacion_destino integer NULL REFERENCES ubicacion(id_ubicacion),
  cantidad numeric(18,3) NOT NULL,
  referencia varchar(100) NULL,
  id_usuario integer NULL REFERENCES usuario(id_usuario),
  observaciones varchar(255) NULL
);

CREATE TABLE IF NOT EXISTS colaborador (
  id_colaborador integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_colaborador varchar(20) NOT NULL UNIQUE,
  nombre varchar(100) NOT NULL,
  apellido varchar(100) NOT NULL,
  puesto varchar(100) NULL,
  area varchar(100) NULL,
  activo boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS maquina (
  id_maquina integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_articulo integer NOT NULL REFERENCES articulo(id_articulo),
  codigo_maquina varchar(50) NOT NULL UNIQUE,
  numero_serie varchar(100) NULL,
  modelo varchar(100) NULL,
  marca varchar(100) NULL,
  estado varchar(30) NOT NULL DEFAULT 'OPERATIVA',
  en_uso boolean NOT NULL DEFAULT false,
  id_ubicacion_actual integer NULL REFERENCES ubicacion(id_ubicacion),
  observaciones varchar(255) NULL
);

CREATE TABLE IF NOT EXISTS herramienta_unidad (
  id_herramienta integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_articulo integer NOT NULL REFERENCES articulo(id_articulo),
  codigo_herramienta varchar(50) NOT NULL UNIQUE,
  estado varchar(30) NOT NULL DEFAULT 'DISPONIBLE',
  id_ubicacion_actual integer NULL REFERENCES ubicacion(id_ubicacion),
  observaciones varchar(255) NULL
);

CREATE TABLE IF NOT EXISTS asignacion_herramienta (
  id_asignacion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_herramienta integer NOT NULL REFERENCES herramienta_unidad(id_herramienta),
  id_colaborador integer NOT NULL REFERENCES colaborador(id_colaborador),
  fecha_asignacion timestamptz NOT NULL DEFAULT now(),
  fecha_devolucion timestamptz NULL,
  estado varchar(20) NOT NULL DEFAULT 'ACTIVA',
  observaciones varchar(255) NULL
);

CREATE TABLE IF NOT EXISTS uso_maquina (
  id_uso integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_maquina integer NOT NULL REFERENCES maquina(id_maquina),
  id_colaborador integer NULL REFERENCES colaborador(id_colaborador),
  fecha_inicio timestamptz NOT NULL DEFAULT now(),
  fecha_fin timestamptz NULL,
  ot varchar(50) NULL,
  observaciones varchar(255) NULL
);

INSERT INTO usuario (username, password_hash)
VALUES ('admin', 'admin')
ON CONFLICT (username) DO NOTHING;

INSERT INTO ubicacion (codigo_ubicacion, nombre_ubicacion, tipo_ubicacion)
VALUES
  ('SUBENSAMBLE', 'AREA DE SUBENSAMBLE', 'INTERNA'),
  ('STOCK', 'AREA DE STOCK', 'INTERNA'),
  ('CONSUMIBLES', 'AREA DE CONSUMIBLES', 'INTERNA'),
  ('PROYECTO', 'PROYECTO', 'EXTERNA')
ON CONFLICT (codigo_ubicacion) DO NOTHING;

INSERT INTO categoria (codigo_categoria, nombre_categoria)
VALUES
  ('10', 'MATERIA PRIMA'),
  ('30', 'SEMI-TERMINADO'),
  ('40', 'PRODUCTO TERMINADO')
ON CONFLICT (codigo_categoria) DO NOTHING;

INSERT INTO subcategoria (id_categoria, codigo_subcategoria, nombre_subcategoria)
SELECT c.id_categoria, '201', 'MATERIALES PARA FABRICACION DUCTOS (FABRICA)'
FROM categoria c
WHERE c.codigo_categoria = '10'
ON CONFLICT (id_categoria, codigo_subcategoria) DO NOTHING;

INSERT INTO subcategoria (id_categoria, codigo_subcategoria, nombre_subcategoria)
SELECT c.id_categoria, '201', 'SUBENSAMBLES'
FROM categoria c
WHERE c.codigo_categoria = '30'
ON CONFLICT (id_categoria, codigo_subcategoria) DO NOTHING;

INSERT INTO subcategoria (id_categoria, codigo_subcategoria, nombre_subcategoria)
SELECT c.id_categoria, '201', 'DUCTOS REDONDOS'
FROM categoria c
WHERE c.codigo_categoria = '40'
ON CONFLICT (id_categoria, codigo_subcategoria) DO NOTHING;

INSERT INTO colaborador (codigo_colaborador, nombre, apellido, puesto, area)
VALUES
  ('COL_SUP', 'MARIPAZ', 'APELLIDO1', 'ROL', 'FABRICA'),
  ('COL_TI', 'JOSE P', 'BARRANTES', 'ADMIN SISTEMA', 'TI')
ON CONFLICT (codigo_colaborador) DO NOTHING;

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

