CREATE TABLE IF NOT EXISTS categoria (
  id_categoria integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_categoria char(2) NOT NULL UNIQUE,
  nombre_categoria varchar(100) NOT NULL,
  activo boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS subcategoria (
  id_subcategoria integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_categoria integer NOT NULL REFERENCES categoria(id_categoria),
  codigo_subcategoria char(3) NOT NULL,
  nombre_subcategoria varchar(100) NOT NULL,
  activo boolean NOT NULL DEFAULT true,
  CONSTRAINT uq_subcat UNIQUE (id_categoria, codigo_subcategoria)
);

CREATE TABLE IF NOT EXISTS articulo (
  id_articulo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_articulo bigint NOT NULL UNIQUE,
  codigo_sap bigint NULL,
  id_categoria integer NOT NULL REFERENCES categoria(id_categoria),
  id_subcategoria integer NOT NULL REFERENCES subcategoria(id_subcategoria),
  nombre_base varchar(150) NOT NULL,
  descripcion varchar(255) NULL,
  dimension_principal varchar(50) NULL,
  detalle_adicional varchar(255) NULL,
  unidad_medida varchar(20) NOT NULL,
  es_maquinaria boolean NOT NULL DEFAULT false,
  es_herramienta boolean NOT NULL DEFAULT false,
  es_consumible boolean NOT NULL DEFAULT false,
  activo boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS ubicacion (
  id_ubicacion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_ubicacion varchar(50) NOT NULL UNIQUE,
  nombre_ubicacion varchar(150) NOT NULL,
  tipo_ubicacion varchar(50) NOT NULL,
  activa boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS stock (
  id_stock integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_articulo integer NOT NULL REFERENCES articulo(id_articulo),
  id_ubicacion integer NOT NULL REFERENCES ubicacion(id_ubicacion),
  cantidad_actual numeric(18,3) NOT NULL DEFAULT 0,
  minimo numeric(18,3) NOT NULL DEFAULT 0,
  maximo numeric(18,3) NOT NULL DEFAULT 0,
  punto_reorden numeric(18,3) NOT NULL DEFAULT 0,
  fecha_ultima_actualizacion timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_stock UNIQUE (id_articulo, id_ubicacion)
);

CREATE TABLE IF NOT EXISTS usuario (
  id_usuario integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(50) NOT NULL UNIQUE,
  password_hash varchar(255) NOT NULL,
  activo boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS movimiento_stock (
  id_movimiento integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_hora timestamptz NOT NULL DEFAULT now(),
  tipo_movimiento varchar(20) NOT NULL,
  id_articulo integer NOT NULL REFERENCES articulo(id_articulo),
  id_ubicacion_origen integer NULL REFERENCES ubicacion(id_ubicacion),
  id_ubicacion_destino integer NULL REFERENCES ubicacion(id_ubicacion),
  cantidad numeric(18,3) NOT NULL,
  referencia varchar(100) NULL,
  id_usuario integer NULL REFERENCES usuario(id_usuario),
  observaciones varchar(255) NULL
);

CREATE TABLE IF NOT EXISTS colaborador (
  id_colaborador integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_colaborador varchar(20) NOT NULL UNIQUE,
  nombre varchar(100) NOT NULL,
  apellido varchar(100) NOT NULL,
  puesto varchar(100) NULL,
  area varchar(100) NULL,
  activo boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS maquina (
  id_maquina integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_articulo integer NOT NULL REFERENCES articulo(id_articulo),
  codigo_maquina varchar(50) NOT NULL UNIQUE,
  numero_serie varchar(100) NULL,
  modelo varchar(100) NULL,
  marca varchar(100) NULL,
  estado varchar(30) NOT NULL DEFAULT 'OPERATIVA',
  en_uso boolean NOT NULL DEFAULT false,
  id_ubicacion_actual integer NULL REFERENCES ubicacion(id_ubicacion),
  observaciones varchar(255) NULL
);

CREATE TABLE IF NOT EXISTS herramienta_unidad (
  id_herramienta integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_articulo integer NOT NULL REFERENCES articulo(id_articulo),
  codigo_herramienta varchar(50) NOT NULL UNIQUE,
  estado varchar(30) NOT NULL DEFAULT 'DISPONIBLE',
  id_ubicacion_actual integer NULL REFERENCES ubicacion(id_ubicacion),
  observaciones varchar(255) NULL
);

CREATE TABLE IF NOT EXISTS asignacion_herramienta (
  id_asignacion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_herramienta integer NOT NULL REFERENCES herramienta_unidad(id_herramienta),
  id_colaborador integer NOT NULL REFERENCES colaborador(id_colaborador),
  fecha_asignacion timestamptz NOT NULL DEFAULT now(),
  fecha_devolucion timestamptz NULL,
  estado varchar(20) NOT NULL DEFAULT 'ACTIVA',
  observaciones varchar(255) NULL
);

CREATE TABLE IF NOT EXISTS uso_maquina (
  id_uso integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_maquina integer NOT NULL REFERENCES maquina(id_maquina),
  id_colaborador integer NULL REFERENCES colaborador(id_colaborador),
  fecha_inicio timestamptz NOT NULL DEFAULT now(),
  fecha_fin timestamptz NULL,
  ot varchar(50) NULL,
  observaciones varchar(255) NULL
);

CREATE TABLE IF NOT EXISTS fabricacion_asociacion (
  id_asociacion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_subensamble integer NOT NULL REFERENCES articulo(id_articulo),
  id_producto_terminado integer NOT NULL REFERENCES articulo(id_articulo),
  activa boolean NOT NULL DEFAULT true,
  fecha_creacion timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_fabricacion_asociacion_sub UNIQUE (id_subensamble)
);

CREATE TABLE IF NOT EXISTS app_user (
  user_id uuid PRIMARY KEY,
  email text NULL,
  role text NOT NULL DEFAULT 'user',
  active boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION sync_app_user_from_auth()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  domain text;
  is_admin boolean;
  next_role text;
  next_active boolean;
BEGIN
  IF NEW.email IS NULL THEN
    RETURN NEW;
  END IF;

  domain := split_part(lower(NEW.email), '@', 2);
  IF domain <> 'climatisacr.com' THEN
    RETURN NEW;
  END IF;

  next_active := false;

  SELECT EXISTS (
    SELECT 1 FROM public.app_user u WHERE u.role = 'admin' AND u.active = true
  ) INTO is_admin;
  next_role := CASE WHEN is_admin THEN 'user' ELSE 'admin' END;

  INSERT INTO public.app_user (user_id, email, role, active, created_at, updated_at)
  VALUES (NEW.id, NEW.email, next_role, next_active, now(), now())
  ON CONFLICT (user_id) DO UPDATE SET
    email = EXCLUDED.email,
    active = EXCLUDED.active,
    updated_at = now();

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_app_user_from_auth ON auth.users;
CREATE TRIGGER trg_sync_app_user_from_auth
AFTER INSERT OR UPDATE OF email, email_confirmed_at
ON auth.users
FOR EACH ROW
EXECUTE FUNCTION sync_app_user_from_auth();

CREATE OR REPLACE FUNCTION app_is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM app_user u
    WHERE u.user_id = auth.uid()
      AND u.role = 'admin'
      AND u.active = true
  );
$$;

ALTER TABLE app_user ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS app_user_select ON app_user;
CREATE POLICY app_user_select
ON app_user
FOR SELECT
USING (user_id = auth.uid() OR app_is_admin());

DROP POLICY IF EXISTS app_user_insert_own_pending ON app_user;
CREATE POLICY app_user_insert_own_pending
ON app_user
FOR INSERT
WITH CHECK (user_id = auth.uid() AND role = 'user' AND active = false);

DROP POLICY IF EXISTS app_user_admin_insert ON app_user;
CREATE POLICY app_user_admin_insert
ON app_user
FOR INSERT
WITH CHECK (app_is_admin());

DROP POLICY IF EXISTS app_user_admin_update ON app_user;
CREATE POLICY app_user_admin_update
ON app_user
FOR UPDATE
USING (app_is_admin())
WITH CHECK (app_is_admin());

DROP POLICY IF EXISTS app_user_admin_delete ON app_user;
CREATE POLICY app_user_admin_delete
ON app_user
FOR DELETE
USING (app_is_admin());

ALTER TABLE categoria DISABLE ROW LEVEL SECURITY;
ALTER TABLE subcategoria DISABLE ROW LEVEL SECURITY;
ALTER TABLE articulo DISABLE ROW LEVEL SECURITY;
ALTER TABLE ubicacion DISABLE ROW LEVEL SECURITY;
ALTER TABLE stock DISABLE ROW LEVEL SECURITY;
ALTER TABLE usuario DISABLE ROW LEVEL SECURITY;
ALTER TABLE movimiento_stock DISABLE ROW LEVEL SECURITY;
ALTER TABLE colaborador DISABLE ROW LEVEL SECURITY;
ALTER TABLE maquina DISABLE ROW LEVEL SECURITY;
ALTER TABLE herramienta_unidad DISABLE ROW LEVEL SECURITY;
ALTER TABLE asignacion_herramienta DISABLE ROW LEVEL SECURITY;
ALTER TABLE uso_maquina DISABLE ROW LEVEL SECURITY;
ALTER TABLE fabricacion_asociacion DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_user DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_user ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_subcategoria_id_categoria ON subcategoria(id_categoria);
CREATE INDEX IF NOT EXISTS idx_articulo_id_categoria ON articulo(id_categoria);
CREATE INDEX IF NOT EXISTS idx_articulo_id_subcategoria ON articulo(id_subcategoria);
CREATE INDEX IF NOT EXISTS idx_stock_id_articulo ON stock(id_articulo);
CREATE INDEX IF NOT EXISTS idx_stock_id_ubicacion ON stock(id_ubicacion);
CREATE INDEX IF NOT EXISTS idx_mov_stock_id_articulo ON movimiento_stock(id_articulo);
CREATE INDEX IF NOT EXISTS idx_mov_stock_id_ubi_origen ON movimiento_stock(id_ubicacion_origen);
CREATE INDEX IF NOT EXISTS idx_mov_stock_id_ubi_destino ON movimiento_stock(id_ubicacion_destino);
CREATE INDEX IF NOT EXISTS idx_maquina_id_articulo ON maquina(id_articulo);
CREATE INDEX IF NOT EXISTS idx_herramienta_id_articulo ON herramienta_unidad(id_articulo);
CREATE INDEX IF NOT EXISTS idx_asig_herr_id_herramienta ON asignacion_herramienta(id_herramienta);
CREATE INDEX IF NOT EXISTS idx_asig_herr_id_colaborador ON asignacion_herramienta(id_colaborador);
CREATE INDEX IF NOT EXISTS idx_uso_maquina_id_maquina ON uso_maquina(id_maquina);
CREATE INDEX IF NOT EXISTS idx_fab_asoc_id_pt ON fabricacion_asociacion(id_producto_terminado);
CREATE INDEX IF NOT EXISTS idx_app_user_active_role ON app_user(active, role);

INSERT INTO usuario (username, password_hash)
VALUES ('admin', 'admin')
ON CONFLICT (username) DO NOTHING;

INSERT INTO ubicacion (codigo_ubicacion, nombre_ubicacion, tipo_ubicacion)
VALUES
  ('SUBENSAMBLE', 'AREA DE SUBENSAMBLE', 'INTERNA'),
  ('STOCK', 'AREA DE STOCK', 'INTERNA'),
  ('CONSUMIBLES', 'AREA DE CONSUMIBLES', 'INTERNA'),
  ('PROYECTO', 'PROYECTO', 'EXTERNA')
ON CONFLICT (codigo_ubicacion) DO NOTHING;

INSERT INTO categoria (codigo_categoria, nombre_categoria)
VALUES
  ('10', 'MATERIA PRIMA'),
  ('30', 'SEMI-TERMINADO'),
  ('40', 'PRODUCTO TERMINADO')
ON CONFLICT (codigo_categoria) DO NOTHING;

INSERT INTO subcategoria (id_categoria, codigo_subcategoria, nombre_subcategoria)
SELECT c.id_categoria, '201', 'MATERIALES PARA FABRICACION DUCTOS (FABRICA)'
FROM categoria c
WHERE c.codigo_categoria = '10'
ON CONFLICT (id_categoria, codigo_subcategoria) DO NOTHING;

INSERT INTO subcategoria (id_categoria, codigo_subcategoria, nombre_subcategoria)
SELECT c.id_categoria, '201', 'SUBENSAMBLES'
FROM categoria c
WHERE c.codigo_categoria = '30'
ON CONFLICT (id_categoria, codigo_subcategoria) DO NOTHING;

INSERT INTO subcategoria (id_categoria, codigo_subcategoria, nombre_subcategoria)
SELECT c.id_categoria, '201', 'DUCTOS REDONDOS'
FROM categoria c
WHERE c.codigo_categoria = '40'
ON CONFLICT (id_categoria, codigo_subcategoria) DO NOTHING;

INSERT INTO colaborador (codigo_colaborador, nombre, apellido, puesto, area)
VALUES
  ('COL_SUP', 'MARIPAZ', 'APELLIDO1', 'ROL', 'FABRICA'),
  ('COL_TI', 'JOSE P', 'BARRANTES', 'ADMIN SISTEMA', 'TI')
ON CONFLICT (codigo_colaborador) DO NOTHING;

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
GRANT EXECUTE ON FUNCTION app_is_admin() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION sync_app_user_from_auth() TO anon, authenticated;
